version: '3'
services:
  django:
    build: .
    command: gunicorn --bind  0.0.0.0:8000 project.wsgi:application
    volumes:
      - static:/code/static_root
      - media:/code/media
    expose:
      - 8000
  nginx:
      image: nginx:1.13
      ports:
        - "80:80"
      volumes:
        - ./nginx_confd:/etc/nginx/conf.d
        - static:/code/static_root
        - media:/code/media
      depends_on:
        - django

volumes:
    static:
    media:
